server {
    listen 80 default_server;
    listen 3001 default_server;
    server_name salinacomunidades.salina.com.br 192.168.4.227;

    root /home/comunidade-form/form_comunidade_salina/frontend/dist;
    index index.html;

    # Logs
    access_log /var/log/nginx/comunidade_access.log;
    error_log /var/log/nginx/comunidade_error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        
        # Headers recomendados para proxy reverso
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }
}
